### PR TITLE
Localization managers

### LINKED ISSUE #293: Problem with localization loading
One line from our error log:

```
Caused by: java.nio.file.NoSuchFileException: /opt/codingteam/horta-hell/src/main/resources/localization
```

That's urgent, we need to fix that ASAP.

### PR DESCRIPTION
**Pull request by ForNeVeR**
I've implemented two distinct localization managers to load the localization data either from the file system or from the embedded resources. Resource loading will be the default and the only option.

It will fix #293 and #294.

### CODE REVIEW

**Comment by ForNeVeR** [comment]
cc @rexim

File: src/main/scala/ru/org/codingteam/horta/localization/ResourceLocalizationLister.scala [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+    }
+  }
+
+  override def getReader(localeName: String): Reader = {
+    if (isJarFile) {
+      getJarReader(localeName)
+    } else {
+      fileLister.getReader(localeName)
+    }
+  }
```
Comment (rexim) [inline src/main/scala/ru/org/codingteam/horta/localization/ResourceLocalizationLister.scala]: @j123123 would not approve this :)

**Comment by rexim** [comment]
I approve this shit!
